language: java
install: true
os: linux
jdk:
- openjdk11
- openjdk13
script:
- "./gradlew clean test"
env:
  global:
  - secure: Z0VMlegVZ81Fs/uOVOAs83mJiyu8XOG+TP+avM/+lbG4vD8FfbZ1nsjsUhQ94HbvfL6Q1xsazn+/xIjvAH2UTqCwXaf2YkjeiTOzWmxZHZQPIDeKxCQoIPBanwH04QaTEGwLrKd9nXTzo7emdV1ho/qoc1T9Nxj2bM4EyYVn4Mj7sMRuUNGOztd1NIFI4jO9sdYxf4vF9O3BxDxLEjTWC53purxIjXFkfecGu/l77bXGbVQm/a31YRRq7Sqhz6im4o2QjO1NQa/kQoLMeBCoBxJQ9VJn95GUkCpcU/VogLivcc+hz9NlQmoNHsV2t3AW2k8sCYALZvxq6X33/+YSCHhd7U80sLu2TIdLgzWoDZEw5BZTjbL/lOKJMuVlpPeDUIrRC1AenBrgeFA6JC9qOf4+kGp13OdXQw4njDy9FP5kJfIn1z+Szeh60XVrxd+UZnaQnIHaw1iLvm+9kO0y2yAFqg8ky4Z8PUvRhZf/x0TdDbYIO5Js/J3FUVSveipA1zsaIm5nTCv7azdZFXwrqjrDqcD6Sn5QxUZuPqk1I1GtZRgLV1wGkXfXoHqjm1cuSvlZFrPIQBZDYqfUNifb8f59c+ZpzTnVDffRFyq347PIKV3NIIkgIQlTqDrv0EC7SH4qMp3Dbgt35TRE8SGLPHFN688ovr8ghmOuOSeEBJM=
  - secure: knEdrZ/kN08TE5ZK0osKiIOQ/gRPjvnUQQgAh9BWd154kYy+2WRgnh7Fq3FJDFAAqvJPkQsfVK/UC06nZmaiCLLwW5a2yMpm7JBGWFULvF1aKOAcMOU7LIURkDjpoSmDlYwMgquG5hHw1nGmc1r2L601BYDLhYN+Ttw5Cb37OICVF5dyQCFZnBukBRLh+vMS0M8zV4kBo9/RYfNpYhtwBAmGH6J5NxNBG1mteJaO7e0sqD+NJ0Wl4pkAtNWk8d3RwrlLVXDCe3xuKwbkT+Q/d+RD3m493hum/bdIdEK+I+APENcWoeLOC15eBxSqcLFzGyDmv8lB62cgklD+nOm+ktV24v8iEQBBBqi5l5OTAGFtWpJpe6NIOBkj17QbeR27IR7JcnRUk1akwU6Wg5K9s6KC5bHa8pZmUtCjbmFTAdDtwJb9R13OfJOQc/yid5uJQDF20OJ0Qvxf1tXGdu9X/NKT6xETP1aP4JgVupBn20Q0TYnKfzRGv1x5gvl6o0D/1wJdau+/iwu/nVct0vgpsxDaYvFi1F6Z5W+sA2dbswbqa855DC8ID7XOap9lN2wgMWxSjsxJ6Qg1gBI4pVZ925QTIkzxM602ktCyQq/3tw6FAsmO4jPbeZWFTkWWW9UrxHT/nhX30fF/CFMfCrTwE4wGtiJnPkXSQHecRcYsVMw=
